#+TITLE:  Materials for ARE212
#+AUTHOR: Ethan Ligon

For class-related conversations, please go to [[https://piazza.com/class/km9z4xiuham24j][piazza.com]].

* General Policies
  Discussion of administrative issues: [[[https://drive.google.com/file/d/1lrcl99dxnaH2APiQ7d5EwppcpMbhpM8-][video]]]

** Grading
*** Final Exam
    The final exam will be "take-home", and be made available by 11am on
    Monday, May 9 (if there is a *consensus* that an earlier date is
    preferable then we can reschedule).  You will have 24 hours to
    complete the final.

*** Groups
    You should regard yourself as a member of a *group*, and your
    group will be responsible for working together on certain
    assignments.  Group sizes should be between 3--6 (inclusive).  

*** Discussions & Exercises
    We will provide a combination of exercises and problems for
    discussion.  These are in lieu of formal individual problem sets.  
**** Exercises
    You are *required* to work on the exercises with other students in
    the class.  Your *group* should turn in /one/ set of notes and
    proposed solutions to the exercises.   I will provide a set of
    exercises for each of our major topics.   These are called
    /exercises/ because they are meant more as tests of comprehension
    than as more difficult /problems/.  Exercises will be graded on a
    "check", "check +", "check -" system.  

    Not turning in an exercise will be much worse for the grades of
    people in your group than receiving a "check -".

**** Discussions
    /Problems/ will be the focus of broader class discussion on =piazza.com=.  Your
    participation and contributions in these discussions will be
    /individually/ graded.

    My intention is to post different discussion prompts every week.
    There are two things (well, five) I then ask of you each week: 

       - Respond to /two/ or more of my discussion prompts.  
         Please post these responses earlier rather than later.

       - Comment on at least /three/ of the posts responding to the
         discussion prompt (i.e., comment on others comments).  A
         livelier discussion will result if you don't wait until the
         last minute to post these comments, so that there's some
         opportunity for dialog.  
 
    The goal here is to have constructive discussions, to help us all
    in our thinking about interesting topics in econometrics.  Our
    "grading" of your remarks will be restricted to counting them and
    to noting when we think your remarks are good (we'll "like" them).
    The bar for a good remark isn't really very high--we just want to
    see that you're contributing constructively to the conversation.
    We're basically looking for active, constructive participation.
    It's perfectly fine for you to have little filler remarks, like
    "great question!", but we'd hope to see other remarks with more
    substantive thought or content.

    The main way to receive a poor individual assessment for the
    discussions is not to participate in them.  If you feel shy about
    sharing your thoughts with the class, piazza allows you to post in
    such a way that your classmates can't identify you (you could also
    post fully anonymously, but in this case the instructors can't
    give you credit).

** Readings
  - "Hansen" refers to Bruce Hansen's [[https://www.ssc.wisc.edu/~bhansen/econometrics/Econometrics.pdf][Econometrics Textbook]].  This is
    freely available on-line, and is soon to be published by Princeton.
  - Unresolved references of the form "cite:foo84" or similar are keys
    with values that can be looked up in
    [[file:are212.bib][are212.bib]].  This last is a bibtex database which
    you're free to use.  The bibtex file includes some links to pdf
    files which you may find useful.
* Other Resources
** Friday Sections
   Lucy Hackett will hold weekly sections on Fridays.  She'll present
   material pertaining to both econometrics and programming.

   It's critical to note that we expect you to develop some fluency in
   the programming language =python=.  

** HowTos
   - GitHub :: How to view, files, fork, edit, and issue pull requests
     (PRs).  https://youtu.be/krDQk5ZzP8U
   - GitHub to DataHub :: How to use datahub to run & edit code from
     github:  https://youtu.be/HBM8jgvYPtA
   - Python Bootcamp :: [[[http://datahub.berkeley.edu/user-redirect/interact?account=acwatt&repo=are212-bootcamp&branch=master&path=][datahub]]][[[https://github.com/acwatt/are212-bootcamp][github]]]

* Topics
   Discussion of topics for 2nd half of course: [[https://drive.google.com/file/d/1MmyeW71lNVixYoXcuJTHjdBk-Fu7kpq_][[video]]]
** Multiple Equation Models
** Some Non-parametrics
** Causality & Correlation
** Identification & Instrumental Variables
** Generalized Method of Moments
** Discrete Choice & Maximum Likelihood
** Resampling &  the Bootstrap
** Cross-Validation & Other Ideas from Machine Learning
* Future Topics                                                    :noexport:
** Multiple Equation Models
   - Lecture: Multiple Linear Equation Models I [[https://github.com/ligonteaching/ARE212_Materials/blob/master/multiple_regression.pdf][[pdf]]][[[https://drive.google.com/file/d/1ULO_v8_g-lIWLdU0af7SW_kax_8vht5o][video]]]
   - Reading
     - Hansen Ch. 11.  General contemporary reference on systems of
       linear regressions.
     - [[https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse][Moore-Penrose Pseudo-Inverse]]
     - [[https://xkcd.com/1132/][Munroe (2012)]].  Did the sun just explode?
     - fullcite:haavelmo44.  Classic discussion of the "probability
       approach" to estimating economic models; one of the key
       documents distinguishing econometrics from statistics.
     - fullcite:christ94.  Discussion of the birth of econometrics at
       the Cowles Commission; beyond its historical importance, worth
       reading to understand the source of much of the jargon we now use.
     - cite:stock-trebbi03,wright1921,wright1928 (Appendix B).  On the
       origins of instrumental variables.  The Wright papers are some
       of the earliest and clearest discussions of identification.
   - Jupyter notebooks
     - [[file:random_variables0.ipynb][random_variables0.ipynb]]
     - [[file:classical_regression.ipynb][classical_regression.ipynb]]
     - [[file:weighted_regression.ipynb][weighted_regression.ipynb]]
** Some Non-parametrics (Kernel methods)
   - Reading
     - Non-parametric Density Estimation, Chapter 17 in [[https://www.ssc.wisc.edu/~bhansen/probability/Intro2Metrics.pdf][Hansen's Introduction to Econometrics]]
     - Hansen Ch. 19 (Non-parametric regression)
** Causality & Correlation
   - [[file:causality_and_correlation.pdf][Notes on Causality & Correlation]]
   - Reading
     - fullcite:frisch30.  Highly insightful and only recently
       published lectures Frisch gave at Yale in 1930.
     - fullcite:haavelmo43.  A founding document of the structural
       (Cowles Commission) approach to economics.
     - fullcite:haavelmo44.  Classic statement regarding the
       "probability approach" to economics.
     - fullcite:goldberger72. Insightful, historically informed
       reflections on identification of structural models in economics.
     - fullcite:pearl15,heckman-pinto15,pearl13.  Back and forth between Pearl
       & Heckman/Pinto.  They agree on one thing: Frisch & Haavelmo were right.
     - fullcite:pearl09.  Pearl's textbook on causality.  
     - fullcite:friedman53.  Classic essay on the usefulness of
       "falsifying" economic models and the role of assumptions.
     - Stanford Encyclopedia of Philosophy, [[https://stanford.library.sydney.edu.au/archives/sum2016/entries/induction-problem/]["The Problem of Induction"]]
     - Hume, [[https://www.gutenberg.org/files/9662/9662-h/9662-h.htm][An enquiry concerning human understanding]]
     - Sewell Wright
       https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1200501/pdf/111.pdf
     - fullcite:imbens-rubin15.  Up-to-date statement and discussion of
       the Neyman-Rubin potential outcomes model, with focus on the assignment model.
     - fullcite:heckman10.  Contemporary survey comparing "reduced
       form" and "structural" approaches to causal inference.
     - fullcite:heckman97.  Critique of potential outcome approach in
       program evaluation.
     - https://www.smbc-comics.com/comic/marshmallow-test
   - Jupyter notebooks
     - [[file:wright34.ipynb][wright34.ipynb]]
** Identification & Instrumental Variables
   - [[https://github.com/ligonteaching/ARE212_Materials/blob/master/iv_notes.pdf][Notes on Identification and Instrumental Variables]]

   - Reading
     - Hansen Chapter 12
     - fullcite:angrist-krueger01
     - fullcite:conley-etal12
     - fullcite:chernozhukov-hansen08  
   - Data
     - [[https://github.com/ligonteaching/ARE212_Materials/blob/master/angrist-krueger91.dta][Angrist-Krueger (1991)]]
** Generalized Method of Moments
   - [[https://github.com/ligonteaching/ARE212_Materials/blob/master/gmm_notes.pdf][Notes on GMM]]
   - Reading
     - Hansen Chapter 13
     - Review normal linear regression model (E.g., Hansen Chapter 5)
     - fullcite:chamberlain87
     - fullcite:newey-west87a
   - Further notes on [[https://github.com/ligonteaching/ARE212_Materials/blob/master/gmm_estimation.pdf][GMM Estimation]]
   - Jupyter notebook exploring GMM in finite samples
     ([[https://github.com/ligonteaching/ARE212_Materials/blob/master/gmm_finite_samples.ipynb][github]]/[[http://datahub.berkeley.edu/user-redirect/interact?account=ligonteaching&repo=ARE212_Materials&branch=master&path=gmm_finite_samples.ipynb][datahub]])
** Resampling & the Bootstrap
  - [[https://github.com/ligonteaching/ARE212_Materials/blob/master/bootstrapping_notes.pdf][Notes on Data Generating Processes and the Bootstrap]]
  - Reading
    - Hansen Chapter 10
** Cross-Validation & Other Ideas from Machine Learning
  - fullcite:friedman53
  - Reading
    - Hansen Section 22.6
  - Hansen Chapter 23
  - Jupyter notebook comparing MLE & Nonlinear-IV estimation of a Logit model 
    ([[https://github.com/ligonteaching/ARE212_Materials/blob/master/gmm_logit.ipynb][github]]/[[http://datahub.berkeley.edu/user-redirect/interact?account=ligonteaching&repo=ARE212_Materials&branch=master&path=gmm_logit.ipynb][datahub]])
  - Notes on [[https://github.com/ligonteaching/ARE212_Materials/blob/master/loss_penalty.pdf][Loss-Penalty Estimation]]
  - Jupyter notebook on [[https://github.com/ligonteaching/ARE212_Materials/blob/master/linear-non-linear.ipynb][linear estimation of non-linear functions]] ([[http://datahub.berkeley.edu/user-redirect/interact?account=ligonteaching&repo=ARE212_Materials&branch=master&path=linear-non-linear.ipynb][datahub]])
   
#+LATEX: \printbibliography
